name: TUDortmundMLSeminar
dependencies:
  - python=2.7
  - keras
  - tensorflow
  - h5py
  - numpy
  - matplotlib
  - ipython
  - scikit-learn
  - pandas
  - scipy
  - mlxtend
  - seaborn

  - pip:
    - wget
    - pydot
    - graphviz
    - pydotprint

